In [1]:
import numpy as np
b=np.array([[[[10,8,15,6,11,12,6],[29,29,30,28,26,20,21]],
             [[14,13,8,-13,6,12,7],[25,29,25,27,27,22,28]],
             [[10,15,14,14,13,6,14],[23,27,23,24,23,29,30]],
            [[8,13,10,13,6,11,6],[22,32,26,22,27,27,21]]],
           [[[6,15,8,9,14,15,11],[27,24,28,20,27,28,29]],
           [[13,14,10,11,9,9,10],[24,28,27,25,22,27,27]],
           [[13,10,7,12,10,8,13],[29,20,21,24,27,28,30]],
           [[10,9,12,6,6,9,12],[25,32,30,30,23,20,21]]],
           [[[7,2,7,5,5,6,22],[21,21,18,19,22,22,8]],
           [[4,5,6,7,6,7,22],[21,22,21,19,20,4,6]],
           [[2,6,6,7,4,4,22],[18,19,19,19,18,6,7]],
           [[4,5,3,8,7,5,20],[22,18,22,22,18,5,2]]],
           [[[9,9,-10,11,12,8,21],[19,22,22,19,19,71,10]],
           [[8,7,7,7,11,12,22],[20,21,18,18,21,8,11]],
           [[9,7,12,9,11,7,22],[22,21,18,18,18,8,11]],
           [[7,10,7,11,11,10,19],[19,20,22,20,20,12,11]]]])
print('ques-1_temperatures of four months(nov,dec,jan,feb) of jaipur:-\n',b)

ques-1_temperatures of four months(nov,dec,jan,feb) of jaipur:-
 [[[[ 10   8  15   6  11  12   6]
   [ 29  29  30  28  26  20  21]]

  [[ 14  13   8 -13   6  12   7]
   [ 25  29  25  27  27  22  28]]

  [[ 10  15  14  14  13   6  14]
   [ 23  27  23  24  23  29  30]]

  [[  8  13  10  13   6  11   6]
   [ 22  32  26  22  27  27  21]]]


 [[[  6  15   8   9  14  15  11]
   [ 27  24  28  20  27  28  29]]

  [[ 13  14  10  11   9   9  10]
   [ 24  28  27  25  22  27  27]]

  [[ 13  10   7  12  10   8  13]
   [ 29  20  21  24  27  28  30]]

  [[ 10   9  12   6   6   9  12]
   [ 25  32  30  30  23  20  21]]]


 [[[  7   2   7   5   5   6  22]
   [ 21  21  18  19  22  22   8]]

  [[  4   5   6   7   6   7  22]
   [ 21  22  21  19  20   4   6]]

  [[  2   6   6   7   4   4  22]
   [ 18  19  19  19  18   6   7]]

  [[  4   5   3   8   7   5  20]
   [ 22  18  22  22  18   5   2]]]


 [[[  9   9 -10  11  12   8  21]
   [ 19  22  22  19  19  71  10]]

  [[  8   7   7   7  11  12  22]
   [ 20  21 

In [2]:
print('ques.2_shape of created numpy array:-')
b.shape


ques.2_shape of created numpy array:-


(4, 4, 2, 7)

In [3]:
print('since there are four indexies, therefore it is a "4-D array".\n\neach index represent particular value i.e.:\nfirst index(4) represent four months.\nsecond index(4) represent four weeks of each month.\nthird index(2) represent min and max temp respectively.\nforth index(7) represent 7 days of each week.')

since there are four indexies, therefore it is a "4-D array".

each index represent particular value i.e.:
first index(4) represent four months.
second index(4) represent four weeks of each month.
third index(2) represent min and max temp respectively.
forth index(7) represent 7 days of each week.


In [4]:
print('ques.3_daily temps of first week of each month:-')
b[:,0,:,:]

ques.3_daily temps of first week of each month:-


array([[[ 10,   8,  15,   6,  11,  12,   6],
        [ 29,  29,  30,  28,  26,  20,  21]],

       [[  6,  15,   8,   9,  14,  15,  11],
        [ 27,  24,  28,  20,  27,  28,  29]],

       [[  7,   2,   7,   5,   5,   6,  22],
        [ 21,  21,  18,  19,  22,  22,   8]],

       [[  9,   9, -10,  11,  12,   8,  21],
        [ 19,  22,  22,  19,  19,  71,  10]]])

In [5]:
print('ques.4_temp of tuesdays of every month:-')
b[0:,0:,0:,1]

ques.4_temp of tuesdays of every month:-


array([[[ 8, 29],
        [13, 29],
        [15, 27],
        [13, 32]],

       [[15, 24],
        [14, 28],
        [10, 20],
        [ 9, 32]],

       [[ 2, 21],
        [ 5, 22],
        [ 6, 19],
        [ 5, 18]],

       [[ 9, 22],
        [ 7, 21],
        [ 7, 21],
        [10, 20]]])

In [6]:
print('ques.5_the max temp for all the weekdays of the months of dec and feb:')
b[1:4:2,0:,1,0:5]

ques.5_the max temp for all the weekdays of the months of dec and feb:


array([[[27, 24, 28, 20, 27],
        [24, 28, 27, 25, 22],
        [29, 20, 21, 24, 27],
        [25, 32, 30, 30, 23]],

       [[19, 22, 22, 19, 19],
        [20, 21, 18, 18, 21],
        [22, 21, 18, 18, 18],
        [19, 20, 22, 20, 20]]])

In [70]:
#6
a=b[0,:,0,:]
u=np.where(a<8)#index
u

(array([0, 0, 1, 1, 2, 3, 3], dtype=int64),
 array([3, 6, 4, 6, 5, 4, 6], dtype=int64))

In [8]:
weeks={0:'week1',1:'week2',2:'week3',3:'week4'}

In [9]:
day={0:'mon',1:'tues',2:'wed',3:'thur',4:'fri',5:'sat',6:'sun'}

In [10]:
print('ques.6_all the days along with week no. in nov when the min temp was less than 8 degrees:')
for i in range(len(u[0])):
    print(weeks[u[0][i]],day[u[1][i]])

ques.6_all the days along with week no. in nov when the min temp was less than 8 degrees:
week1 thur
week1 sun
week2 thur
week2 fri
week2 sun
week3 sat
week4 fri
week4 sun


In [11]:
#7:
a=b[1:3,:,1,:]
v=np.where(a>20)

In [12]:
month={0:'dec',1:'jan'}

In [42]:
#7:
print('ques.7_all the weeks in dec and jan where the max temp has crossed a threshold of 20 degrees:')
for i in range(len(v[0])):
    print(month[v[0][i]],weeks[v[1][i]])


ques.7_all the weeks in dec and jan where the max temp has crossed a threshold of 20 degrees:
dec week1
dec week1
dec week1
dec week1
dec week1
dec week1
dec week2
dec week2
dec week2
dec week2
dec week2
dec week2
dec week2
dec week3
dec week3
dec week3
dec week3
dec week3
dec week3
dec week4
dec week4
dec week4
dec week4
dec week4
dec week4
jan week1
jan week1
jan week1
jan week1
jan week2
jan week2
jan week2
jan week4
jan week4
jan week4


In [53]:
print('ques.8_all the absurd values:\n absurd values are those values which is illogical or not related to the rest of the data present.\n yes, there are some absurd values present in the given data, those are:')
un=np.unique(b)
un

ques.8_all the absurd values:
 absurd values are those values which is illogical or not related to the rest of the data present.
 yes, there are some absurd values present in the given data, those are:


array([ 2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14, 15, 17, 18, 19,
       20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 32])

In [50]:
print("ques.9_we'll replace the absurd values with the mean or average of that particular month.")

ques.9_we'll replace the absurd values with the mean or average of that particular month.


In [58]:
print("ques.10_we'll find the outliers/unusual values with the help of lower and upper temp ranges of each month.\n unusual min temp will by that temp which is lower than the lower temp range.\n and unusual max temp will by that temp which is greater than upper temp range.")

ques.10_we'll find the outliers/unusual values with the help of lower and upper temp ranges of each month.
 unusual min temp will by that temp which is lower than the lower temp range.
 and unusual max temp will by that temp which is greater than upper temp range.


In [55]:
iqr=np.percentile(b,75)-np.percentile(b,25)

In [56]:
#nov
uu=np.mean(b[0])-1.5*iqr#lower
vv=np.mean(b[0])+1.5*iqr#upper

In [60]:
print('the lower and upper temp ranges for the month of nov:')
uu,vv

the lower and upper temp ranges for the month of nov:


(-2.8571428571428577, 39.14285714285714)

In [62]:
gg=np.where(b[0]<uu)
print('indexies of all the unusual values for the month of nov:')
gg

indexies of all the unusual values for the month of nov:


(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [26]:
hh=np.where(b[0]>vv)
hh

(array([], dtype=int64), array([], dtype=int64), array([], dtype=int64))

In [27]:
#dec
uuu=np.mean(b[1])-1.5*iqr#lower
vvv=np.mean(b[1])+1.5*iqr#upper
uuu,vvv

(-2.8928571428571423, 39.10714285714286)

In [28]:
ggg=np.where(b[1]<uuu)
hhh=np.where(b[1]>vvv)
hhh,ggg

((array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)),
 (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)))

In [29]:
#jan
uuuu=np.mean(b[2])-1.5*iqr#lower
vvvv=np.mean(b[2])+1.5*iqr#upper
uuuu,vvvv

(-8.982142857142858, 33.01785714285714)

In [30]:
gggg=np.where(b[2]<uuuu)
hhhh=np.where(b[2]>vvvv)
hhhh,gggg

((array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)),
 (array([], dtype=int64), array([], dtype=int64), array([], dtype=int64)))

In [31]:
#feb
uuuuu=np.mean(b[3])-1.5*iqr#lower
vvvvv=np.mean(b[3])+1.5*iqr#upper
uuuuu,vvvvv

(-6.267857142857142, 35.73214285714286)

In [32]:
ggggg=np.where(b[3]<uuuuu)
hhhhh=np.where(b[3]>vvvvv)
hhhhh,ggggg

((array([0], dtype=int64), array([1], dtype=int64), array([5], dtype=int64)),
 (array([0], dtype=int64), array([0], dtype=int64), array([2], dtype=int64)))

In [34]:
b[0][b[0]<uu]=np.mean(b[0,:,0,:])
b[0][b[0]>vv]=np.mean(b[0,:,1,:])
b

array([[[[ 10,   8,  15,   6,  11,  12,   6],
         [ 29,  29,  30,  28,  26,  20,  21]],

        [[ 14,  13,   8,   9,   6,  12,   7],
         [ 25,  29,  25,  27,  27,  22,  28]],

        [[ 10,  15,  14,  14,  13,   6,  14],
         [ 23,  27,  23,  24,  23,  29,  30]],

        [[  8,  13,  10,  13,   6,  11,   6],
         [ 22,  32,  26,  22,  27,  27,  21]]],


       [[[  6,  15,   8,   9,  14,  15,  11],
         [ 27,  24,  28,  20,  27,  28,  29]],

        [[ 13,  14,  10,  11,   9,   9,  10],
         [ 24,  28,  27,  25,  22,  27,  27]],

        [[ 13,  10,   7,  12,  10,   8,  13],
         [ 29,  20,  21,  24,  27,  28,  30]],

        [[ 10,   9,  12,   6,   6,   9,  12],
         [ 25,  32,  30,  30,  23,  20,  21]]],


       [[[  7,   2,   7,   5,   5,   6,  22],
         [ 21,  21,  18,  19,  22,  22,   8]],

        [[  4,   5,   6,   7,   6,   7,  22],
         [ 21,  22,  21,  19,  20,   4,   6]],

        [[  2,   6,   6,   7,   4,   4,  22],
         [

In [36]:
#12:
int(np.mean(b[0:,0:,1,:]))#np.average(b[index]) se bi same ans aa jaega

21

In [37]:
#13:
 int(np.average(b[1,:,0,:]))

IndentationError: unexpected indent (3342820294.py, line 2)

In [ ]:
#14:
int(np.average(b[1:3,:,:,:]))

In [ ]:
#15(part1):min temp in dec
q=np.amin(b[1,:,:,:])
q

In [ ]:
#15(part1):min temp in jan
w=np.amin(b[2,:,:,:])
w

In [71]:
#15(part2):#position of least temp in dec
a=b[1,:,:,:]
h=np.where(a==np.amin(b[1,:,:,:]))
h

(array([0, 3, 3], dtype=int64),
 array([0, 0, 0], dtype=int64),
 array([0, 3, 4], dtype=int64))

In [72]:
#15(part2);#position of least temp in jan
a=b[2,:,:,:]
e=np.where(a==np.amin(b[2,:,:,:]))
e

(array([0, 2, 3], dtype=int64),
 array([0, 0, 1], dtype=int64),
 array([1, 0, 6], dtype=int64))

In [73]:
months={0:'nov',1:'dec',2:'jan',3:'feb'}

In [74]:
#15(part2):day,week,month for least temp in dec
for i in range(len(h[0])):
    print(day[h[2][i]],weeks[h[1][i]],months[h[0][i]])

mon week1 nov
thur week1 feb
fri week1 feb


In [75]:
#15(part2):day,week,month for least temp in jan
for i in range(len(e[0])):
    print(day[e[2][i]],weeks[e[1][i]],months[e[0][i]])

tues week1 nov
mon week1 jan
sun week2 feb


In [76]:
#16:max temp in feb
np.amax(b[3,:,1,:])

22

In [77]:
#16:position
a=b[3,:,1,:]
t=np.where(a==np.amax(b[3,:,1,:]))
t

(array([0, 0, 2, 3], dtype=int64), array([1, 2, 0, 2], dtype=int64))

In [78]:
#16:day and week of max temp for feb
for i in range(len(t[0])):
    print(day[t[1][i]],weeks[t[0][i]])

tues week1
wed week1
mon week3
wed week4


In [82]:
#17:(avg temp of the month)
y=int(np.average(b[0,:,:,:]))
y

18

In [80]:
#17:
a=b[0,:,:,:]
o=np.where(b[0,:,1,:]<y)
o
#empty arrays since there are no days where the max temp of the day dropped by the avg temp 

(array([], dtype=int64), array([], dtype=int64))

In [ ]:
#18:

In [48]:
#19_
for i in range(len(b)):
    n=(b*1.8)+32
    print(n)

[[[[50.  46.4 59.  42.8 51.8 53.6 42.8]
   [84.2 84.2 86.  82.4 78.8 68.  69.8]]

  [[57.2 55.4 46.4 55.4 42.8 53.6 44.6]
   [77.  84.2 77.  80.6 80.6 71.6 82.4]]

  [[50.  59.  57.2 57.2 55.4 42.8 57.2]
   [73.4 80.6 73.4 75.2 73.4 84.2 86. ]]

  [[46.4 55.4 50.  55.4 42.8 51.8 42.8]
   [71.6 89.6 78.8 71.6 80.6 80.6 69.8]]]


 [[[42.8 59.  46.4 48.2 57.2 59.  51.8]
   [80.6 75.2 82.4 68.  80.6 82.4 84.2]]

  [[55.4 57.2 50.  51.8 48.2 48.2 50. ]
   [75.2 82.4 80.6 77.  71.6 80.6 80.6]]

  [[55.4 50.  44.6 53.6 50.  46.4 55.4]
   [84.2 68.  69.8 75.2 80.6 82.4 86. ]]

  [[50.  48.2 53.6 42.8 42.8 48.2 53.6]
   [77.  89.6 86.  86.  73.4 68.  69.8]]]


 [[[44.6 35.6 44.6 41.  41.  42.8 71.6]
   [69.8 69.8 64.4 66.2 71.6 71.6 46.4]]

  [[39.2 41.  42.8 44.6 42.8 44.6 71.6]
   [69.8 71.6 69.8 66.2 68.  39.2 42.8]]

  [[35.6 42.8 42.8 44.6 39.2 39.2 71.6]
   [64.4 66.2 66.2 66.2 64.4 42.8 44.6]]

  [[39.2 41.  37.4 46.4 44.6 41.  68. ]
   [71.6 64.4 71.6 71.6 64.4 41.  35.6]]]


 [[[48.2 4

In [64]:
#20_
aa=np.average(b[1,0,:,:])
print('average temp of first week of dec:\t',aa)
bb=np.average(b[1,1,:,:])
print('average temp of second week of dec:\t',bb)
cc=np.average(b[1,2,:,:])
print('average temp of third week of dec:\t',cc)     
dd=np.average(b[1,3,:,:])
print('average temp of forth week of dec:\t',dd)

average temp of first week of dec:	 18.642857142857142
average temp of second week of dec:	 18.285714285714285
average temp of third week of dec:	 18.0
average temp of forth week of dec:	 17.5


In [67]:
j=[dd,cc,bb,aa]
j.sort()
j

[17.5, 18.0, 18.285714285714285, 18.642857142857142]

In [38]:
print('week4:',b[1,3,:,:],'< week3:',b[1,2,:,:],'< week2:',b[1,1,:,:],'< week1:',b[1,0,:,:])

week4: [[10  9 12  6  6  9 12]
 [25 32 30 30 23 20 21]] < week3: [[13 10  7 12 10  8 13]
 [29 20 21 24 27 28 30]] < week2: [[13 14 10 11  9  9 10]
 [24 28 27 25 22 27 27]] < week1: [[ 6 15  8  9 14 15 11]
 [27 24 28 20 27 28 29]]


In [43]:
#21_
k=np.average(b)
k

15.598214285714286

In [83]:
#22_
b[:,:,1,:]-b[:,:,0,:]

array([[[ 19,  21,  15,  22,  15,   8,  15],
        [ 11,  16,  17,  14,  21,  10,  21],
        [ 13,  12,   9,  10,  10,  23,  16],
        [ 14,  19,  16,   9,  21,  16,  15]],

       [[ 21,   9,  20,  11,  13,  13,  18],
        [ 11,  14,  17,  14,  13,  18,  17],
        [ 16,  10,  14,  12,  17,  20,  17],
        [ 15,  23,  18,  24,  17,  11,   9]],

       [[ 14,  19,  11,  14,  17,  16, -14],
        [ 17,  17,  15,  12,  14,  -3, -16],
        [ 16,  13,  13,  12,  14,   2, -15],
        [ 18,  13,  19,  14,  11,   0, -18]],

       [[ 10,  13,  12,   8,   7,   9, -11],
        [ 12,  14,  11,  11,  10,  -4, -11],
        [ 13,  14,   6,   9,   7,   1, -11],
        [ 12,  10,  15,   9,   9,   2,  -8]]])

In [84]:
#23_
ii=b[:,:,1,0:6:2]-b[:,:,1,1:7:2]
ii

array([[[  0,   2,   6],
        [ -4,  -2,   5],
        [ -4,  -1,  -6],
        [-10,   4,   0]],

       [[  3,   8,  -1],
        [ -4,   2,  -5],
        [  9,  -3,  -1],
        [ -7,   0,   3]],

       [[  0,  -1,   0],
        [ -1,   2,  16],
        [ -1,   0,  12],
        [  4,   0,  13]],

       [[ -3,   3,   2],
        [ -1,   0,  13],
        [  1,   0,  10],
        [ -1,   2,   8]]])

In [85]:
#24_
oo=b[:,:,0,0:6:2]-b[:,:,0,1:7:2]
oo

array([[[ 2,  9, -1],
        [ 1, -5, -6],
        [-5,  0,  7],
        [-5, -3, -5]],

       [[-9, -1, -1],
        [-1, -1,  0],
        [ 3, -5,  2],
        [ 1,  6, -3]],

       [[ 5,  2, -1],
        [-1, -1, -1],
        [-4, -1,  0],
        [-1, -5,  2]],

       [[ 0, -1,  4],
        [ 1,  0, -1],
        [ 2,  3,  4],
        [-3, -4,  1]]])

In [86]:
#25_
np.concatenate((ii,oo),axis=0)

array([[[  0,   2,   6],
        [ -4,  -2,   5],
        [ -4,  -1,  -6],
        [-10,   4,   0]],

       [[  3,   8,  -1],
        [ -4,   2,  -5],
        [  9,  -3,  -1],
        [ -7,   0,   3]],

       [[  0,  -1,   0],
        [ -1,   2,  16],
        [ -1,   0,  12],
        [  4,   0,  13]],

       [[ -3,   3,   2],
        [ -1,   0,  13],
        [  1,   0,  10],
        [ -1,   2,   8]],

       [[  2,   9,  -1],
        [  1,  -5,  -6],
        [ -5,   0,   7],
        [ -5,  -3,  -5]],

       [[ -9,  -1,  -1],
        [ -1,  -1,   0],
        [  3,  -5,   2],
        [  1,   6,  -3]],

       [[  5,   2,  -1],
        [ -1,  -1,  -1],
        [ -4,  -1,   0],
        [ -1,  -5,   2]],

       [[  0,  -1,   4],
        [  1,   0,  -1],
        [  2,   3,   4],
        [ -3,  -4,   1]]])